# Generated by Django 5.0.6 on 2024-06-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='subCategory',
        ),
    ]
